---
- name: "End play if distribution not suported"
  meta: end_host
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: "Install requierements"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ adminer_packages }}"

- name: "Ensure install dir exist"
  file:
    path: '{{ adminer_install_dir }}'
    state: directory
    owner: '{{ adminer_owner }}'
    group: '{{ adminer_group }}'
    mode: '0755'

- name: "Download adminer files"
  get_url:
    url: '{{ adminer_src_url }}'
    dest: '{{ adminer_install_dir }}/index.php'
    owner: '{{ adminer_owner }}'
    group: '{{ adminer_group }}'
    mode: '0766'
