---
### INCLUDE META
- name: Include roles' meta data
  include_vars:
    file: "{{ role_path }}/meta/main.yml"

### TEST DISTRIB
- name: Test the distribution is supported. End the host if not.
  set_fact:
    supported_distributions: "{{ galaxy_info.platforms|json_query('[].name') }}"
- debug:
    var: supported_distributions
- block:
    - debug:
        msg: "{{ ansible_distribution }} not supported. End of host."
    - meta: end_host
  when: ansible_distribution not in supported_distributions

### TEST RELEASE
- name: Test the release is supported. End the host if not.
  set_fact:
    supported_releases: "{{ (galaxy_info.platforms| selectattr('name', 'match', ansible_distribution)| list|first).versions }}"
- debug:
    var: supported_releases
- block:
    - debug:
        msg: "{{ ansible_distribution_release}} not supported. End of host."
    - meta: end_host
  when: ansible_distribution_release not in supported_releases

- name: The distribution and release is supported. Continue play.
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} is supported. Continue play."

### PLAY ROLE
- name: Import play tasks
  import_tasks: play.yml


- name: "Check for adminer files"
  stat:
    path: "{{ adminer_install_dir }}/index.php"
  changed_when: false
  register: adminer_install

- name: "Get current version"
  shell: /usr/bin/grep @version {{ adminer_install_dir}}/index.php | awk '{print $NF}'
  changed_when: false
  register: adminer_install_version
  when: adminer_install.stat.exists

- name: Installation process
  when: (not adminer_install.stat.exists) or (adminer_install_version is defined and adminer_version not in adminer_install_version.stdout)
  block:
    - name: "Install requierements"
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ adminer_packages }}"

    - name: "Ensure install dir exist"
      file:
        path: '{{ adminer_install_dir }}'
        state: directory
        owner: '{{ adminer_owner }}'
        group: '{{ adminer_group }}'
        mode: '0755'

    - name: "Download adminer files"
      get_url:
        url: '{{ adminer_src_url }}'
        dest: '{{ adminer_install_dir }}/index.php'
        owner: '{{ adminer_owner }}'
        group: '{{ adminer_group }}'
        mode: '0766'
